### ISSUE TITLE
Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.

### ISSUE THREAD

**Issue by FlyingGardenGnomeStudios** [ath67/scrbd_book_ripper#10]
The program has been working wonderfully when suddenly I got this error today.
I tried from a different computer and got the exact same error.

```
c:\Python\Python38\scrbd_book_ripper>python main.py install

DevTools listening on ws://127.0.0.1:52637/devtools/browser/e3809c3f-3f37-4a63-8296-c3f6ff22e9a1
[2836:16744:0721/183221.370:ERROR:device_event_log_impl.cc(208)] [18:32:21.370] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.
Traceback (most recent call last):
  File "main.py", line 91, in <module>
    screenshots.screenshot(read_url, book_title, email, password, book_id)  #whole login and screenshot process. Check
  File "c:\Python\Python38\scrbd_book_ripper\base.py", line 157, in screenshot
    self.check_language() #check if its in Portugues and if not, change
  File "c:\Python\Python38\scrbd_book_ripper\base.py", line 44, in check_language
    language = self.driver.find_element_by_xpath('/html/body/span[1]/div/header/div[1]/div[3]/div[1]/div/div/a/span[2]').text
  File "c:\Python\Python38\lib\site-packages\selenium-3.141.0-py3.8.egg\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "c:\Python\Python38\lib\site-packages\selenium-3.141.0-py3.8.egg\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "c:\Python\Python38\lib\site-packages\selenium-3.141.0-py3.8.egg\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\Python\Python38\lib\site-packages\selenium-3.141.0-py3.8.egg\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/span[1]/div/header/div[1]/div[3]/div[1]/div/div/a/span[2]"}
  (Session info: chrome=84.0.4147.89)
```

**Comment by FlyingGardenGnomeStudios** [comment]
additional info:

I tried it from a separate network as some reports on the same subject were saying it has to do with certain vpn settings and I received a different error notice before the "bluetooth error". Not sure if it will help the debugging. I'm a complete ignoramus when it comes to python.

`[7820:18300:0722/183554.007:ERROR:CONSOLE(1)] "Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'strict-dynamic' 'sha256-1+GSDjMMklBjZY0QiWq+tGupCvajw4Xbn46ect2mZgM=' 'sha256-2mX1M62Fd0u8q0dQY2mRsK5S1NS9jJuQAvyE8tD0dkQ=' 'sha256-EtIKSV82ixJHE3AzqhoiVbUGKG+Kd8XS0fFToow29o0=' 'sha256-QSyFltV9X3gkyBrg+SMfKvZNXmqPQc6K4B6OYhTuXmw=' 'sha256-4M0jdrILwm/h3mCRbjIF07jAlCbI0ZbyLjQL/9HVhwE=' 'sha256-CbH+xPsBKQxVw5d9blISLDeuMSe1M+dJ4xfArFynIfw=' 'sha256-C9ctze2LhHtwL+fcPVPkmVRYjQgXTGs4xfBAzlQwGWk=' 'sha256-yVmlm9txUAL9c9wAcTXYqdk4zxtPoJO/pyl4aKclgK8='". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
", source: chrome-search://local-ntp/local-ntp.html (1)
[7820:18300:0722/183558.352:ERROR:device_event_log_impl.cc(208)] [18:35:58.351] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.
Traceback (most recent call last):`

**Comment by ath67** [comment]
Sorry for delayed answers. It does not seems to be related to the Bluetooth error, it is not necessary to the script and i had this error showing all the time here too. The true problem relies on the other lines of the log (first one you sent). I will have to take a look to check if scribd changed anything in theirs website xpaths, if so, it probably will trigger other errors after this one (related to checking the website language) is corrected. 

I'm a bit busy right now but will take a look as soon as possible. Feel free to comment here if I take too long, please.

**Comment by Yaco** [comment]
I am getting this error:

```
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/span[1]/div/header/div[1]/div[3]/div[1]/div/div/a/span[2]"}

```

Thanks!

**Comment by ath67** [comment]
I was checking the website, and it seems there were changes in the html structure (very minor changes but they affect us), so the script can't find the elements in the page to confirm what it needs. This one is the first error, if you change the code to `/html/body/span[1]/div/header/div[1]/div[3]/div[1]/div/div` it will pass this error, but will probably happen in another place and all. I will need to check every xpath in the script. I'm currently working out to be independent of xpaths, but will need more time for this.
Sorry for delayed answers, I'm on a lot of projects right now. :woozy_face:

**Comment by ThePutois** [comment]
Happening to me as well, where can we modify the script to add this line of code? thanks

**Comment by FlyingGardenGnomeStudios** [comment]
I had tried the fix, but must have screwed up somehow, so just tracing the HTML structure I came up with this and it works 
For those like me who know nothing of python, edit the "base.py" file and replace lines 42-50 with:

    #Checks if its in Portuguese version of the site and if not, make the change    
    def check_language(self):
        language = self.driver.find_element_by_xpath('/html/body/span[1]/div[1]/header[1]/div[1]/div[3]/div[1]/div[1]/div[1]/span[1]/a[1]/span[2]').text
        if language != 'PT' or language != 'pt':
            self.driver.find_element_by_xpath('/html/body/span[1]/div/header/div[1]/div[3]/div[1]/div/div/span/a/span[2]').click()
            self.driver.find_element_by_xpath('/html/body/span[1]/div/header/div[1]/div[3]/div[1]/div/div/div/span/div[1]/ul/li[3]/a').click()
            print('Setting language to Portuguese')
        else:
            print('Right site language!')

**Comment by FlyingGardenGnomeStudios** [comment]
You'll also want to change line 164 to:

        self.driver.find_element_by_xpath('/html/body/div[2]/div/div[2]/div[1]/div[1]/div/div/div/section/div/div/section/a').click()

**Comment by ath67** [comment]
> You'll also want to change line 164 to:
> 
> ```
>     self.driver.find_element_by_xpath('/html/body/div[2]/div/div[2]/div[1]/div[1]/div/div/div/section/div/div/section/a').click()
> ```

Actually you will need to upadte any line that uses references from Xpaths. Sorry about that but when writing the script it gave a lot of errors when I tried other approachs, and Scribd chances minimal stuff in their structure every time so it changes the Xpaths. I'm really having trouble with my personal life so I can't put time into it, sorry guys. You should be able to correct this xpaths with the Inspect Element tool from any browser.
