### ISSUE TITLE
PDFTextExtractionNotAllowed

### ISSUE THREAD

**Issue by Mohawk7** [ath67/scrbd_book_ripper#13]
Hi,
I get that error message executing the script : 
`ImportError: cannot import name 'PDFTextExtractionNotAllowed' from 'pdfminer.pdfdocument' (/usr/local/lib/python3.7/dist-packages/pdfminer/pdfdocument.py)
`
Would you know how to fix it ?
Thanks for helping !

**Comment by ath67** [comment]
Hey,could you explain a bit more how are you running everything? This error seems to be related to pdf protected files,which should not have anything to do with the script, because no protection is generated to any of the pdfs before processing.

If you could explain more about how you are running this, would be good. I also recommend testing to separate an specific folder to the script files, just don't run anywhere, put it in a folder just for it before starting. Maybe it is trying to OCR some pdfs that you have in the same folder(?).

**Comment by Mohawk7** [comment]
Thanks for your help.
Actually I don't have any skills in informatic so I already fought to update Python to 3.6 and install all the necessary modules. After I configure the config files (with my email, the passsword, 'True' to liste, 'False' to OCR), I put the chromedriver file (ChromeDriver 85.0.4183.38 linux 64 version)  in the same folder  then I go to the folder in a terminal and do: `ptyhon3 main.py` 

I get   :

> Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import ocrmypdf
  File "/usr/local/lib/python3.7/dist-packages/ocrmypdf/__init__.py", line 21, in <module>
    from ocrmypdf import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "/usr/local/lib/python3.7/dist-packages/ocrmypdf/pdfinfo/__init__.py", line 19, in <module>
    from ocrmypdf.pdfinfo.info import Colorspace, Encoding, PdfInfo
  File "/usr/local/lib/python3.7/dist-packages/ocrmypdf/pdfinfo/info.py", line 37, in <module>
    from ocrmypdf.pdfinfo.layout import get_page_analysis, get_text_boxes
  File "/usr/local/lib/python3.7/dist-packages/ocrmypdf/pdfinfo/layout.py", line 29, in <module>
    from pdfminer.pdfdocument import PDFTextExtractionNotAllowed
ImportError: cannot import name 'PDFTextExtractionNotAllowed' from 'pdfminer.pdfdocument' 
 (/usr/local/lib/python3.7/dist-packages/pdfminer/pdfdocument.py)

I'm a noob so I'm not sure i do the protocol the right way.

**Comment by ath67** [comment]
It seems to be an error with the ocrmypdf version. Could you try to update it and try again? 

Try this:
`pip install ocrmypdf --upgrade`

Please tell me if it fixes the problem!

**Comment by Mohawk7** [comment]
No it doesn't, I get the exact same message. I also tried to uninstall the ocrmypdf module and install it but it doesn't change anything neither.

**Comment by Mohawk7** [comment]
Well, I fixed it by installing the module Pdfminer, seems to be necessary to ocrmypdf.
Now I've a new problem with chromedriver, I get that : 

> Traceback (most recent call last):
  File "main.py", line 91, in <module>
    screenshots.screenshot(read_url, book_title, email, password, book_id)  #whole login and screenshot process. Check
  File "/home/mohawk/scrbd_book_ripper-master/base.py", line 146, in screenshot
    self.driver = webdriver.Chrome(chrome_options=chrome_options)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by ath67** [comment]
Okay, great. I was going to ask for reinstall pdfminer. 
For the chromedriver, when downloading did you choose the chromedriver version equal to you Chrome installation? It's strange that it is failing to start... Looking you logs you seems to be in Linux, am I right?

**Comment by Mohawk7** [comment]
Yes I'm on Linux but I'm sorry I don't know which Log can be helpful here.

The chromedriver error seems to be [common ](https://stackoverflow.com/questions/8255929/running-selenium-webdriver-python-bindings-in-chrome/24364290#24364290) but it behind my understanding. ..

**Comment by ath67** [comment]
Did you try to run what this user advised? It seems to be an good solution. If you think you are not able I can try to help you or detail it a bit more.

**Comment by Mohawk7** [comment]
Thanks for your help!
In the solution, I don't understand where (and how) to execute the code (step 8) :

> 8. finally you can execute the code.

>> from selenium import webdriver
driver = webdriver.Chrome()
driver.get("http://www.google.com")
print driver.page_source.encode('utf-8')
driver.quit()
display.stop()

Is this in the Sellenium options, in a random script ?

**Comment by ath67** [comment]
Yes, this part is a random script, so you can ignore and test with scrbd_book_ripper

**Comment by Mohawk7** [comment]
Alright, I just did the solution but three things are wrong :
1/ the cmd `chromium-browser -versionsudo` and `apt-get install chromium-browser` don't work in my configuration (Debian Bustr)
2/ the chromedriver versions doesn't feet perfectly with the version installed of chrome-browser in my debian (83.0.4103.116), so I tried with  83.0.4103.14  and 83.0.4103.39 versions.  (ps : I have Chromium and Google Chrome installed)
3/ when I try to use the chromebrower that I placed in usr/bin, I get : 

> Starting ChromeDriver 83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1595940782,734][SEVERE]: bind() failed: Adresse déjà utilisée (98)
IPv6 port not available. Exiting...

Maybe it comes from the installation of Chrome wich seems to be different in Debian ?
