### ISSUE TITLE
can't get the script running

### ISSUE THREAD

**Issue by keneedy** [ath67/scrbd_book_ripper#21]
so i'm trying to run the script without OCR (so i tried setting "Do_OCR": "" and "Do_OCR": "False") but i always get the same error:

Traceback (most recent call last):
  File "F:\Downloads\scrbd_book_ripper-master\scrbd_book_ripper-master\main.py", line 4, in <module>
    import ocrmypdf
  File "C:\Users\adm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ocrmypdf\__init__.py", line 10, in <module>
    from ocrmypdf import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "C:\Users\adm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ocrmypdf\leptonica.py", line 43, in <module>
    raise MissingDependencyError(
ocrmypdf.exceptions.MissingDependencyError:
        ---------------------------------------------------------------------
        This error normally occurs when ocrmypdf can't find the Leptonica
        library, which is usually installed with Tesseract OCR. It could be that
        Tesseract is not installed properly, we can't find the installation
        on your system PATH environment variable.

        The library we are looking for is usually called:
            liblept-5.dll   (Windows)
            liblept*.dylib  (macOS)
            liblept*.so     (Linux/BSD)

        Please review our installation procedures to find a solution:
            https://ocrmypdf.readthedocs.io/en/latest/installation.html
        ---------------------------------------------------------------------

How to properly get around OCR?

**Comment by keneedy** [comment]
I installed tesseract and installed python 64bit (using tesseract 64bit) and now i'm getting this error:

Traceback (most recent call last):
  File "C:\Users\adm\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\scrbd_book_ripper-master\main.py", line 1, in <module>
    import base
  File "C:\Users\adm\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\scrbd_book_ripper-master\base.py", line 10, in <module>
    from PIL import Image
  File "C:\Users\adm\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\adm\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\__init__.py)

**Comment by jaan143** [comment]
i am getting same error of your first 
i installed everything fine

**Comment by rubencanovaca** [comment]
![image](https://user-images.githubusercontent.com/3774332/98807604-32cdd800-241b-11eb-948a-9064d6553462.png)

**Comment by rubencanovaca** [comment]
But I have "Do_OCR": "False"

What happens?
