### ISSUE TITLE
check_language fails

### ISSUE THREAD

**Issue by rubencanovaca** [ath67/scrbd_book_ripper#36]
![image](https://user-images.githubusercontent.com/3774332/98833230-1000eb00-243e-11eb-91a5-b98e15925119.png)

**Comment by ahmedtsadek** [comment]
same for me
`Traceback (most recent call last):
  File "/Users/tharaweto/Downloads/scrbd_book_ripper-master/main.py", line 91, in <module>
    screenshots.screenshot(read_url, book_title, email, password, book_id)  #whole login and screenshot process. Check
  File "/Users/tharaweto/Downloads/scrbd_book_ripper-master/base.py", line 157, in screenshot
    self.check_language() #check if its in Portugues and if not, change
  File "/Users/tharaweto/Downloads/scrbd_book_ripper-master/base.py", line 44, in check_language
    language = self.driver.find_element_by_xpath('/html/body/span[1]/div/header/div[1]/div[3]/div[1]/div/div/a/span[2]').text
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/span[1]/div/header/div[1]/div[3]/div[1]/div/div/a/span[2]"}
  (Session info: chrome=87.0.4280.88)`
