### ISSUE TITLE
Updated xpaths, navigation to link in "Read this book Now", and fix for newline in book title

### ISSUE THREAD

**Issue by ladymileva** [ath67/scrbd_book_ripper#43]
Thank you for this script!  I have made some changes to base.py and main.py so that it would work for me. 

In base.py: 
- Updated xpaths
- Link for book was embedded in "Read this book Now" button, it is now selected and followed correctly
- Appended .rstrip() to book title to remove newline if present

[base.txt](https://github.com/ath67/scrbd_book_ripper/files/5745343/base.txt)  (Change name to base.py)

In main.py: 
- Appended .rstrip() to book_title_cleaned

**Comment by ath67** [comment]
Hey! Great!! Thanks for this work on it. Is it working after this updates? If so, would you mind making a PR to the repo?

Really thanks for this, I’m really busy on other personal projects to keep it working and updated. 🤒

Em 27 de dez de 2020, à(s) 19:26, ladymileva <notifications@github.com> escreveu:

﻿

Thank you for this script! I have made some changes to base.py and main.py so that it would work for me.

In base.py:

  *   Updated xpaths
  *   Link for book was embedded in "Read this book Now" button, it is now selected and followed correctly
  *   Appended .rstrip() to book title to remove newline if present

base.txt<https://github.com/ath67/scrbd_book_ripper/files/5745343/base.txt> (Change name to base.py)

In main.py:

  *   Appended .rstrip() to book_title_cleaned

**Comment by TaoTeCha** [comment]
What was the change to the xpaths that worked for you?

**Comment by RobynWillison** [comment]
I don't know what to do with this info

In main.py:

  *   Appended .rstrip() to book_title_cleaned
 
I have downloaded the new base.txt and renamed it base.py and this is what I get.

python3 main.py 
Setting language to Portuguese
First click to log in done!
Second click to log in done!
none
Clicked Log In buttom
try
Got back to books page
Traceback (most recent call last):
  File "main.py", line 91, in <module>
    screenshots.screenshot(read_url, book_title, email, password, book_id)  #whole login and screenshot process. Check
  File "/home/robyn/Downloads/scrbd_book_ripper-master/base.py", line 167, in screenshot
    self.driver.find_element_by_xpath('/html/body/div[1]/div/div/div/button/span/span[2]').click()
  File "/home/robyn/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/robyn/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/robyn/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/robyn/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div/div/button/span/span[2]"}
  (Session info: chrome=87.0.4280.88)
