### ISSUE TITLE
Proposing new download method

### ISSUE THREAD

**Issue by zavidos** [ath67/scrbd_book_ripper#49]
Hi, I was having many many problems with resolution, all the screenshots downloaded were low quality so I tried a different approach by localising the image in each column and downloading it as jpg through "Requests". This is perfectly working if the book is composed by images only and not if it is text in HTML.
Here is my base.py.
I'm not a developer and I don't know how to contribute with github or if this is the correct procedure (but I doubt it is)
Best regards
Davide

[base.py.txt](https://github.com/ath67/scrbd_book_ripper/files/5771710/base.py.txt)

**Comment by RangerFX4** [comment]
Hi, can you help me to make this work? I copied your base.py and replaced it with the original but I am getting this error. 

```
 C:\Users\admin\Downloads\scrbd_book_ripper>python main.py
 2021-01-06 11:31:38,230 - ERROR - max width: 2480.0
 2021-01-06 11:31:38,230 - ERROR - max height: 3508.0

DevTools listening on ws://127.0.0.1:51825/devtools/browser/7046a089-15de-432a-a7e7-07b89800a333
[7976:12624:0106/113146.844:ERROR:device_event_log_impl.cc(211)] [11:31:46.844] USB: usb_service_win.cc:352 Could not get child device's service name: Element not found. (0x490)
[7976:12624:0106/113146.845:ERROR:device_event_log_impl.cc(211)] [11:31:46.845] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[7976:12624:0106/113146.848:ERROR:device_event_log_impl.cc(211)] [11:31:46.848] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
Traceback (most recent call last):
  File "main.py", line 91, in <module>
    screenshots.screenshot(read_url, book_title, email, password, book_id)  #whole login and screenshot process. Check
  File "C:\Users\admin\Downloads\scrbd_book_ripper\base.py", line 161, in screenshot
    self.check_language() #check if its in Portugues and if not, change
  File "C:\Users\admin\Downloads\scrbd_book_ripper\base.py", line 47, in check_language
    language = self.driver.find_element_by_xpath('//*[@id="global_header"]/div[1]/div[3]/div[1]/div/div/span/a/span[2]').text
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="global_header"]/div[1]/div[3]/div[1]/div/div/span/a/span[2]"}
  (Session info: chrome=87.0.4280.88)
```
